### ISSUE TITLE
redshift does not work in LMDE

### ISSUE THREAD

**Issue by ilali** [jonls/redshift#156]
i have installed redshift 1.7.2 in linux mint LMDE Mate desktop. but it does not work. it does not start working.

**Comment by jonls** [comment]
Can you provide a little more information perhaps? For example, does `redshift` work from the terminal? Are there any error messages? Did you set up the configuration file with the location or are you relying on GeoClue?

**Comment by ilali** [comment]
Yes sure, no it does not work from terminal, i mean when i type redshift in terminal, it shows following message:
```
~ $ redshift
Cannot list GNOME panel applets.
Initialization of gnome-clock failed.
Trying next provider...
Latitude and longitude must be set.
```
also i cannot set location: 
```
~ $ redshift -l LAT:LON
Unknown location provider `LAT'.
```
and the last one but not least, i installed *gtk-redshift* but when i click it's icon, nothing happen.

**Comment by jonls** [comment]
You seem to be using a very old version of Redshift (from 2011) except there never was a 1.7.2 version. I assume you mean 1.7? It tries to get the location from the GNOME panel applet since that worked reasonably well four years ago... it doesn't anymore. You have to upgrade Redshift or set your location manually. In your last approach where you try to set the location you have to _actually put in values for LAT and LON_. How else would Redshift know where you are? Have a look in the man page for an example.

**Comment by ilali** [comment]
Yes, it's version is 1.7-2. it is the latest version available in linux mint LMDE right now. 
what about *gtk-redshift*, what is the problem with that?
how can i install latest version from the source or .deb file?

**Comment by jonls** [comment]
If you get `redshift` working, `gtk-redshift` will work if you specify the same parameters. You can take a look at the file [HACKING.md](https://github.com/jonls/redshift/blob/master/HACKING.md) for more information on building the latest version yourself.
