### ISSUE TITLE
on ubuntu 14.04 redshift master turns the screen all the way to black

### ISSUE THREAD

**Issue by hhuuggoo** [jonls/redshift#161]
/usr/local/bin/redshift -l 40.71:-74.00

redshift v1.10 is fine

**Comment by jonls** [comment]
Would you be able to `git bisect` the problem?

**Comment by christian-burger** [comment]
Can you check if the problem is gone with the patch provided through pull request #162? This sounds as if your symptom could be caused by the issue I fixed there. In my case, the screen went black for a moment before starting to show funky colors as if the display was for view impaired people. Maybe it's a different handling of negative gamma values on your and my system; I don't know ...

**Comment by hhuuggoo** [comment]
not sure how to bisect this - I started a bisect and commit 017fc230be20bf3be605559fcb4cadccaa89b098 passes, however the next commit (from a merge) 9b299132ef8912910df5a90b1628cc3af1efc54d fails with a different error, 

Failed to run Redshift
CRTC 1065353216 does not exist. Valid CRTCs are [0-1065353215].
Temperature adjustment failed.

**Comment by hhuuggoo** [comment]
ok - the CRTC error is a result of me not re-running bootstrap, however it looks like this problem is fixed with @christian-burger master branch, so closing
