### ISSUE TITLE
pkg-config check for Geoclue2 incomplete?

### ISSUE THREAD

**Issue by hartwork** [jonls/redshift#167]
Hi!

`configure.ac` reads:

```
PKG_CHECK_MODULES([GEOCLUE2], [glib-2.0 gio-2.0 >= 2.26], [have_geoclue2=yes], [have_geoclue2=no])
```

My installation of Geoclue 2.1.10 seems to provide its own `.pc` file at `/usr/lib64/pkgconfig/geoclue-2.0.pc`:

```
prefix=/usr
exec_prefix=${prefix}
datarootdir=${prefix}/share
datadir=/usr/share

dbus_interface=${datadir}/dbus-1/interfaces/org.freedesktop.GeoClue2.xml
agent_dbus_interface=${datadir}/dbus-1/interfaces/org.freedesktop.GeoClue2.Agent.xml

Name: Geoclue
Description: The Geoinformation Service
Version: 2.1.10
```

Could it be that an entry `geoclue-2.0` is missing in the call to `PKG_CHECK_MODULES`?

Best, Sebastian

**Comment by jonls** [comment]
I'm not sure about that. We could test for it but we don't really need to. Geoclue is not a requirement to build Redshift since D-Bus is used as the interface.

**Comment by hartwork** [comment]
I'm aware that Geoclue2 is optional. If I un-install Geoclue2 from my system, configure still claims to have found Geoclue2. Compilation seems to succeed anyway since redshift does not link against Geoclue2 anywhere and it does not include any headers of it, either. So you would not notice before runtime. At least the fact that configure claims to have found Geoclue2 is a bug to me, though. If you call that picky, you have a point.

**Comment by jonls** [comment]
Ok, I guess the configure output is not entirely accurate but I don't know if it is possible to easily change that. When the configure script reports that "checking for GEOCLUE2" succeeds you can read that as: the check for the dependencies required to build Geoclue2 support succeeded. I can add a hard requirement for `geoclue-2.0` but that would be an unnecessarily strict check since we don't actually need Geoclue2 to be present at build time. Do you think changing the string GEOCLUE2 in the output of configure to DBUS_CLIENT or something like that would help?

**Comment by hartwork** [comment]
If ..
* geoclue2 is only needed at run time,
* gio and glib are needed at compile time, and
* gio belongs to glib ..

I would suggest to change the check to something like
```
PKG_CHECK_MODULES([GLIB], [glib-2.0 gio-2.0 >= 2.26], [have_glib=yes], [have_glib=no])
```
and use `have_glib` where `have_geoclue2` is being used now. That would be zero mis-communication and not increase complexity. What do you think?

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
