### ISSUE TITLE
"Please report bugs to <https://bugs.launchpad.net/redshift>" in help

### ISSUE THREAD

**Issue by matkoniecz** [jonls/redshift#180]
Message displayed by `redshift -h` ends with 
> Please report bugs to <https://bugs.launchpad.net/redshift>

but http://jonls.dk/redshift/ has

> The project is managed at GitHub where issues and pull requests can also be posted. Please don’t use the old bug tracker at the Launchpad project page anymore.

It is likely to be confusing as https://bugs.launchpad.net/redshift has multiple open bugs.

Present in 1.8 (package for Ubuntu 14.04) but bug was not reported and it seems to be not mentioned on https://github.com/jonls/redshift/releases

See https://github.com/jonls/redshift/blob/0510031b699885e4f4fda594752c6ecd1231742b/po/redshift.pot#L5 or more general https://github.com/jonls/redshift/search?utf8=%E2%9C%93&q=https%3A%2F%2Fbugs.launchpad.net%2Fredshift

**Comment by jonls** [comment]
I think the translation files all have the old URL but that's a really different issue. The URL from the translation files does not actually show up anywhere in the user interface. I think this could be fixed by changing a line in `po/Makevars`.

For the URL displayed by `redshift -h`, the definition comes from one of the first lines in `configure.ac`. It is the third parameter to `AC_INIT` and this is the string that is automatically defined as `PACKAGE_BUGREPORT` in the source code. It has been set to the correct Github URL since version 1.9.

I try to keep track of the bugs reported in Launchpad once in a while to make sure that new bugs are migrated. For example there are two bug reports from 2014 and they are both duplicates of bugs that have already been reported/fixed on Github.

**Comment by jonls** [comment]
I updated `po/Makevars` with the new bug report URL in 88654df6af33b08c04c4784caa8b41bcad649f9c.
