### ISSUE TITLE
Default config could be more conservative

### ISSUE THREAD

**Issue by mmcco** [jonls/redshift#262]
Thanks for developing this - I've been a happy user for about a year. That said, I've introduced a few non-technical friends to Redshift and they've all been really off-put by how extreme the default settings are. Because the GUI doesn't support configuration, they've turned it off until I get a chance to edit `~/.config/redshift.conf` for them.

I think a more reasonable option would be to leave daytime settings unchanged and to set the night-time color temperature to ~4500K.

Thoughts?

**Comment by maandree** [comment]
There are two advantages to not have the daytime temperature set to 6500 K:
1) You will know that Redshift works because it changes the temperature.
2) 6500 K is not good your eyes.

3500 K (defaut for nighttime) may feel a bit extreme at the beginning,
but these values (5500 K – 3500 K) are really good. I think that if you
take the time to install software to make the computer more comfortable
and healthier,  you should expect it to take some time before you are
used to it. And we should not lessen its effectiveness.

Perhaps it is best just explain that it is like learning to eat healthy food.

**Comment by mmcco** [comment]
That may be true, but people don't react with "this could be a healthy learning experience", but rather with "yikes, time to turn this off".

Anyway, the most constructive conclusion is probably that it'd be valuable for the UI to allow changing basic settings. I don't think I'm the person to add that, though.

**Comment by maandree** [comment]
What about starting at 6500–4500, and gradually (perhaps a month) transition into 5500–3500?

**Comment by mmcco** [comment]
Could confuse people, and sounds like a lot of program logic. My perspective on this is that only power-users will want to go below 4500K, and only power-users find it easy to edit a text config file.

**Comment by maandree** [comment]
If there is not config file (or perhaps only that the temperature has not been configured,)
Redshift could keep track of how long you have been using it. Start with values that are
similar to 6500 K, but over time change to more ergonomical values. If we ease the user
into the good values, they will not notice it.
I don't think it will require too much program logic.

**Comment by jonls** [comment]
@mmcco I think those are reasonable suggestions. I will look into changing defaults to 6500K and 4500K.
