### ISSUE TITLE
Configuration in .config/redshift/

### ISSUE THREAD

**Issue by simonnagl** [jonls/redshift#329]
At the moment configuration must be done in `~/.config/redshfit.conf` but hooks are placed in `~/.config/redshift/hooks/`

In my opinion when using hooks accepting `~/.config/redshift/` would be great. If you agree using the second configuration  I would make a pull request for this enhancement.

**Comment by 4l4l2I2M1** [comment]
It's a bit unlucky in my opinion that a configuration must be created first. When you mess a lot with your installation because you have to test several Kernels etc. it's quite annoying to search the example config in the net every time(even when it takes just a few seconds). Especially when you need this amazing program because you noticed how you don't get tired in time with 6500K.

I think the best solution would be to add an option to edit the `~/config/redshift.conf` via redshift-gtk. For most people, setting the range of the color shift as well as the location should be sufficient.

BTW, I think that nearly everyone prefers 6500K for the daytime. Because you can manage to edit photos then and do something else in the night. But you would not do graphical work with 5500K. So the default daytime value would be better at 6500K - imho.

**Comment by jonls** [comment]
Thanks for the suggestion. I wanted to keep `~/.config/redshift/` free in case other kinds of configuration files are needed in the future. For this reason I think the hooks should stay in the `hooks` subdirectory.
