### ISSUE TITLE
Is there an applet that also controls the color temp?

### ISSUE THREAD

**Issue by mladenp** [jonls/redshift#352]
Is there a way to run redshift as an applet and be able to control color temperature from there?
I always use redshift but sometimes when i need to disable it the bright flash just blinds me. 
So i would like to control color temperature from some applet in Ubuntu, is there an easy way to do that?

**Comment by maandree** [comment]
If you enable transitions the flash will disappear.
Currently, redshift does not support what you seek and still have the automatic adjustment.

I'm not sure precisely what you want to do, but I imagine that it is something like this:
When redshift is disable, the colour temperature transitions to 5500 K rather than 6500 K.
If so, you could make this change in redshift's source code and run a custom compilation.

**Comment by mladenp** [comment]
Ideally an Ubuntu applet but a command to lower temp and then easily restore to default settings would also do it.

**Comment by maandree** [comment]
Do you with lower temperature mean more red (which indeed is lower) and with default settings, mean as if redshift was not running? If so, redshift-gtk (included in redshift) is probably what you want.

**Comment by mladenp** [comment]
yeah, i just found out about redshift-gtk, thanks :+1:
