### ISSUE TITLE
Lollypop conflict

### ISSUE THREAD

**Issue by M5oul** [jonls/redshift#373]
Described here: https://github.com/gnumdk/lollypop/issues/773

**Comment by gnumdk** [comment]
Code here: https://github.com/gnumdk/lollypop/blob/master/src/inhibitor.py
Look at __on_status_changed()

**Comment by M5oul** [comment]
https://github.com/gnumdk/lollypop/blob/master/src/inhibitor.py#L89-L97

**Comment by jonls** [comment]
Redshift doesn't listen for or react to suspend inhibition. This sounds more like another program is resetting the gamma ramps which means that a few seconds will pass before Redshift will catch up and reapply the redness effect. You said that this happens when you click play. This suggests to me that the media player backend is resetting the gamma ramps when playback is started. This is something a lot of games and media players seem to be doing. There's not really anything Redshift can do about that since we cannot prevent other programs from changing the gamma ramps.

**Comment by gnumdk** [comment]
Strange:
- Lollypop doesn't change the gamma ramps
- Gstreamer too (I think)

So IMO, it's Gnome Session Manager when receiving SUSPENDING inhibition.
@M5oul Close this issue and go back on lollypop one, will search a workaround...

**Comment by gnumdk** [comment]
@jonls Any easy way to get for gamma ramps? I may be able to disable SUSPENDING if gamma ramps not default.
