### ISSUE TITLE
WB reduction darkens screen + Questions

### ISSUE THREAD

**Issue by anchev** [jonls/redshift#378]
What exactly does preserve do?

> redshift -m randr:help
> Adjust gamma ramps with the X RANDR extension.

  screen=N              X screen to apply adjustments to
  crtc=N                CRTC to apply adjustments to
  preserve={0,1}        Whether existing gamma should be preserved

I am testing on EIZO CG275W screen calibrated in 2 modes: 6500K and 4000K and I wonder how this relates to redshift.

I also notice that if I use redshift the setting of 4000K in it gives quite more red result compared to the calibrated modes of the monitors. redshift at 4000K is also significantly darker than the hardware calibration at 4000K. All this raises the question what hardware mode and redshift settings should be used in order not to experience such color shifts resulting in wrong colors.

I hope you can clarify how to use the software properly in relation to that.
Thanks.

**Comment by maandree** [comment]
@anchev, @jonls, the order the redshift effect and calibration is reversed.
If the effects of redshift is described by the function f(x) and the calibrations
(which fetched by reading the currently gamma ramps when Redshift starts)
is describe the the function g(x), the resulting function when these are combined
should be g(f(x)) but currently is it is f(g(x)).

**Comment by jonls** [comment]
Redshift will give you approximate color temperature settings but will not be able to match hardware calibration exactly. If you use Redshift, you should leave the display at 6500K since Redshift assumes that the display is initially set to this temperature.

Preserve means that you can apply the redness effect on top of any existing calibration of the monitor instead of overriding the calibration.

**Comment by anchev** [comment]
Thanks for explaining jonls.
