### ISSUE TITLE
How to install redshift 1.11?

### ISSUE THREAD

**Issue by NIXOYE** [jonls/redshift#379]
cant seem to find a make file or install file. It would be really nice to include simple install instructions on main github page

**Comment by mattia-b89** [comment]
It's already there!
as the readme says, point to the HACKING.md file

**Comment by NIXOYE** [comment]
@mattia-b89 except that it is outdated and gives instructions to use files that are no longer available in 1.11

**Comment by jonls** [comment]
@NIXOYE how specifically is it outdated? Which files did you not find?

**Comment by NIXOYE** [comment]
@jonls there is no bootstrap file. Thought there was no make file but realized i was getting an error when doing ./configure because i didnt have up to date dependencies

**Comment by jonls** [comment]
It is certainly there: https://github.com/jonls/redshift/blob/master/bootstrap

**Comment by NIXOYE** [comment]
odd, i downloaded the latest release from https://github.com/jonls/redshift/releases and didnt get bootstrap.

Are there any plans on update the repos included in ubuntu to 1.11?

**Comment by jonls** [comment]
Ok, I realize now that you are trying to build from the release archive and not from the master branch. In that case, the `bootstrap` is not needed because the `configure` script is already generated and included in the archive (this may not be obvious but this is standard for projects based on autotools).

Regarding Ubuntu packages, I have no influence on what packages are included in distributions so that's complete up to Ubuntu.
