### ISSUE TITLE
redshift doesn't work with " Option "metamodes" "nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }" "

### ISSUE THREAD

**Issue by sunc9oa** [jonls/redshift#384]
Hi, the redshift doesn't work when I add this option in 20-nvidia.conf

Option "metamodes" "nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"

**Comment by jonls** [comment]
Please report this to Nvidia.

**Comment by dakira** [comment]
@jonls hey. This still seems to be a problem. It was reported to Nvidia [here](https://devtalk.nvidia.com/default/topic/997199/b/t/post/5098466/). Maybe it would help to directly tell the nvidia people what API call isn't working anymore instead of "some random app you've never heard of doesn't work anymore."

**Comment by ajwbae** [comment]
@sunc9oa @dakira I seem to have found a workaround, where if you make a **.desktop** file in your "~/.config/autostart" folder, then edit its properties and give it the command
 
`nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"`

it allows redshift to work with these nvidia settings.

Alternatively, on XFCE, you can do this through **Session and Startup -> Application Autostart** and add an item with the _command_ field having the code above. Hope this helps.
