### ISSUE TITLE
Redshift only starts from terminal now

### ISSUE THREAD

**Issue by Dgameman1** [jonls/redshift#403]
Hello! I downloaded and installed Redshift and it worked perfectly when running from the gnome desktop as well as setting it to startup.

Now, it does not work when I run it as startup, and it does not work if I run it from the gnome desktop.

It only works if I run it in a terminal. This is my terminal log when I run it

```
[daniel@daniel ~]$ redshift -v
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Location: 34.20 N, 118.54 W
Temperatures: 5500K at day, 3400K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Using method `randr'.
Status: Enabled
Period: Night
Color temperature: 6469K
Brightness: 1.00
Color temperature: 6438K
Color temperature: 6407K
A BUNCH OF VALUES IN BETWEEN
Color temperature: 3430K
Color temperature: 3400K
```

**Comment by SLKTH** [comment]
Do you use Fedora or something al like as well?

When I start redshift-gtk I get the following error message:

**Comment by Dgameman1** [comment]
I figured it out on my end. @SLKTH 

Can you run this in a terminal and post the output?

```
python
import sys
print ('\n'.join(sys.path))
exit()
```

**Comment by benguyer** [comment]
Same issue on my end. I have to run "redshift-gtk" then "redshift" to get it to work properly (otherwise there's a geoip error). What was the fix you figured out?

**Comment by Dgameman1** [comment]
@benguyer 

Can you run this in a terminal and post the output?

python
import sys
print ('\n'.join(sys.path))
exit()

**Comment by benguyer** [comment]
Certainly, please let me know if I can do anything else to help.

/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0b3_1874.gb5b5a67-py2.7-linux-x86_64.egg
/usr/local/lib/python2.7/dist-packages/cycler-0.10.0-py2.7.egg
/usr/local/lib/python2.7/dist-packages/subprocess32-3.2.7-py2.7-linux-x86_64.egg
/usr/local/lib/python2.7/dist-packages/functools32-3.2.3_2-py2.7.egg
/usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg
/media/benjamin/Media/src/vplanet/vplanet/vplot
/usr/local/lib/python2.7/dist-packages/pytz-2016.6.1-py2.7.egg
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client

Off topic, but should I'm new to github's interface and community. Should I use code formatting for blocks of text like this? I chose not to here, since it got rid of the line breaks, but that'd be simple enough to fix.

**Comment by Dgameman1** [comment]
@benguyer I'd suggest putting it in code blocks but I personally don't really care lol..

What distro are you using?
And also, shut down redshift and open up terminal and type `redshift -v` and tell me what it says.
Then shut down redshift if it's running and open up terminal and type `redshift-gtk -v` and tell me what it says

**Comment by benguyer** [comment]
Linux Mint 17.2 Cinnamon. In retrospect, this could definitely be a problem with me running an old version, but I can't find a way to tell which version of redshift I'm running. The package is `redshift:amd64/rafaela 1.9.1-1~trusty~ppa3`. Anyway, running `redshift -v` prints out:

`Location: 47.599998, 122.300003
Temperatures: 5500K at day, 3500K at night
Brightness: 1.00:1.00
Gamma: 1.000, 1.000, 1.000
Using method 'randr'.
Status: Enabled
Period: Night
`

Immediately followed by a few dozen lines of:

`"Period: Night
Color temperature: 3500K
Brightness: 1.00
"`

with decreasing temperatures as the program begins to run. This is a bit unexpected because it's definitely not nighttime. Running `redshift-gtk` produces no output and dims the screen as expected.

When I killed the redshift-gtk process with crtl-c it printed an exception with python3.4 in the path. So I thought I'd run the sys.path thing again in python 3. This is what it produced:

    /usr/lib/python3.4
    /usr/lib/python3.4/plat-x86_64-linux-gnu
    /usr/lib/python3.4/lib-dynload
    /usr/local/lib/python3.4/dist-packages
    /usr/lib/python3/dist-packages

**Comment by jonls** [comment]
@benguyer Are you in China? Perhaps your longitude is really -122.3?

**Comment by benguyer** [comment]
No, I'm in Seattle [which has a longitude of -122.3](http://www.latlong.net/place/seattle-wa-usa-2655.html). This is also confirmed using [redshift's own geoclue provider](http://imgur.com/a/Ewv2i). Though, there does seem to be some ambiguity since [Google reports longitude in degrees west for Seattle](https://www.google.com/search?q=seattle+coordinates) and [degrees East for China](https://www.google.com/search?q=beijing+coordinates).

Regardless, the problem persists even without the redshift.conf file, so coordinates don't seem to be the issue here.

**Comment by benguyer** [comment]
Whoops, you're right I got the sign wrong. I copy pasted from Google which gives longitude in [degrees west for some reason](https://www.google.com/search?q=seattle+coordinates).

The issue persists without the redshift.conf file, however. So I don't believe that to be the issue.

**Comment by jonls** [comment]
@benguyer It seems from the output you quoted earlier that the location from GeoClue was also longitude 122.3 (with positive sign). Is that right? Do you know where your GeoClue is configured to obtain location from?

**Comment by benguyer** [comment]
Geoclue has me at [-122.3](http://imgur.com/a/AHfrc), and turns on and off at the proper time.

**Comment by jonls** [comment]
@Dgameman1 sorry, I got your original report sidetracked.

I'm not sure if the issues you all have are related so if it becomes apparent that your issue is unrelated to the original issue by @Dgameman1 please open a new issue then so we can keep this issue report focused. @Dgameman1 can you find any log file for GNOME so we can see why Redshift doesn't work when started from GNOME? Without an error message it's going to be really hard to figure this out.
