### ISSUE TITLE
redshift-gtk doesn't work anymore

### ISSUE THREAD

**Issue by periappi** [jonls/redshift#405]
Hi,

When I start `redshift-gtk` I get the following error : 

> Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib64/python3.4/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    from gi.repository import Gtk, GLib, GObject
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'

Otherwise, the command-line version works properly.

NB : I use Gentoo

**Comment by dirkf** [comment]
See #403 "Redshift only starts from terminal now"

**Comment by jonls** [comment]
This looks like an error that is internal to the `gi` package. Do you still have this issue and have you reported this to Gentoo or asked at the Gentoo forums? They will probably be better able to help you figure this out.

**Comment by hujuice** [comment]
I've the same issue on Gentoo. No similar errors in the forum or in the bugtracker.
But I've three Gentoo/KDE desktops. I've the issue on one of them, a lightweight installation, while I enjoy the others. Could the issue be caused by some missing dependency?
The dependencies listed in the docs (https://github.com/jonls/redshift/blob/master/HACKING.md) seems satisfied everywhere, but what else?

It works where I have a long list of python packages:
dev-python/PyQt4-4.11.4-r1
dev-python/certifi-2016.9.26
dev-python/cffi-1.5.2
dev-python/chardet-2.3.0
dev-python/cryptography-1.5.2
dev-python/dbus-python-1.2.0-r1
dev-python/diff-match-patch-20121119
dev-python/docutils-0.12
dev-python/enum34-1.0.4
dev-python/idna-2.0
dev-python/iniparse-0.4-r2
dev-python/ipaddress-1.0.14
dev-python/lxml-3.6.4-r1
dev-python/m2crypto-0.22.3-r4
dev-python/numpy-1.10.4
dev-python/paramiko-2.0.2
dev-python/pillow-3.4.2-r1
dev-python/ply-3.6-r1
dev-python/pyalsa-1.0.29
dev-python/pyasn1-0.1.8
dev-python/pycairo-1.10.0-r4
dev-python/pycparser-2.14
dev-python/pycups-1.9.73
dev-python/pycurl-7.43.0
dev-python/pyenchant-1.6.6
dev-python/pygments-2.1.1
dev-python/pygobject-2.28.6-r55
dev-python/pygobject-3.20.1
dev-python/pygtk-2.24.0-r4
dev-python/pygtksourceview-2.10.1-r1
dev-python/pylibacl-0.5.0-r1
dev-python/python-dateutil-2.4.2-r1
dev-python/python-levenshtein-0.12.0
dev-python/pyxattr-0.5.5
dev-python/pyxdg-0.25-r1
dev-python/pyyaml-3.12
dev-python/setuptools-20.6.7
dev-python/sip-4.18
dev-python/six-1.10.0
dev-python/translate-toolkit-2.0.0_beta7-r1
dev-python/utidylib-0.3
dev-python/vobject-0.9.3

It doesn't work where I have a short list:
dev-python/PyQt4-4.11.4-r1
dev-python/certifi-2016.9.26
dev-python/dbus-python-1.2.0-r1
dev-python/docutils-0.12
dev-python/numpy-1.10.4
dev-python/pyalsa-1.0.29
dev-python/pycairo-1.10.0-r4
dev-python/pygments-2.1.1
dev-python/pygobject-2.28.6-r55
dev-python/pygobject-3.20.1
dev-python/pygtk-2.24.0-r4
dev-python/pylibacl-0.5.0-r1
dev-python/pyxattr-0.5.5
dev-python/pyxdg-0.25-r1
dev-python/setuptools-20.6.7
dev-python/sip-4.18

Could the the short list miss something?

**Comment by jonls** [comment]
@hujuice Do you have the `_gi.so` file in `/usr/lib64/python3.4/site-packages/gi/`?

**Comment by hujuice** [comment]
No, I don't have _gi.so in the 3.4 version, but I don't have it even in the working systems.
Feel free to ask me more.

**Comment by hujuice** [comment]
I agree, anyway, that it could be related to the Gentoo package. Let's collect infos here and then I'll open a bug there (https://bugs.gentoo.org/).

**Comment by hujuice** [comment]
Solved.
It is absolutely Gentoo related and it is an **error by me, not a bug**.

For @periappi or others in Gentoo, the reason for me was a bad maintenance task related to this: https://www.gentoo.org/support/news-items/2015-12-16-python-abiflags-rebuild-needed.html
Simply run:
emerge -1v $(find /usr/lib*/python3* -name '*cpython-3[3-5].so')
or, for the specific problem, run:
emerge -1v --usepkg n dev-python/pygobject:3

Thanks @jonls.

**Comment by jonls** [comment]
@hujuice 👍  glad you figured it out.
