### ISSUE TITLE
Daytime/Nighttime period wrong

### ISSUE THREAD

**Issue by a-n-t-h-o-n-y** [jonls/redshift#423]
Hi, I'm experiencing a problem where redshift stays in daytime mode until well into the night, it does eventually change to night, seems like its timing is off.
I have double checked the coordinates and the +/- signs. My computer's time is in UTC, maybe that has something to do with it?

**Comment by maandree** [comment]
You're profile since you live in Austin, Texas, so your coordinates should be somewhere around 30:-100, is this correct? When you say that your computer's time is in UTC, do you mean the hardware clock is in UTC not localtime (it is recommended unless you use an old version of windows to use UTC) or do you mean that `date +%Z` prints "UTC" but the clock shows your local time, only if the latter is the case is this a problem.

I would tell you which time it should be night and day for you, but apparently my program acts a little beat weird when I put in your location, so I'm not confident in the output. But as long as the sun is up it should be day, even if it is night by the clock.

**Comment by a-n-t-h-o-n-y** [comment]
Looks like I had the clock settings incorrect, I updated the hardware clock with ntp, everything is working fine now. Thanks for your time!
