### ISSUE TITLE
redshift system tray icon for Windows

### ISSUE THREAD

**Issue by landroni** [jonls/redshift#428]
I am using redshift 1.9.1 on a Windows XP machine and it seems as if the experimental builds provide no system tray icon on Windows. It would be useful if a (minimal) systray icon were available on Windows machines just like on Linux, at least allowing one to close the instance.

**Comment by shunjou** [comment]
I made [an autohotkey script](https://github.com/jonls/redshift/issues/232#issuecomment-167631629) to serve this purpose; since then [this project](http://iristech.co/redshift-gui-0-0-1-for-windows/) has also been created.

**Comment by ltGuillaume** [comment]
...and I just uploaded my [Redshift Tray](https://github.com/ltGuillaume/Redshift-Tray) project to GitHub. It has a few more features like autorun, pause for x minutes, force night mode, double-click to enable/disabled, a beaut of an icon :P and some hotkeys by personal preference. Perhaps it could make someone else very happy, too :)

**Comment by ltGuillaume** [comment]
@shunjou that was a good idea! I needed to create a new AutoHotkey script with hotkeys for my new PC anyway, so I combined it with a no-frills GUI for Redshift, so that it's a full replacement for F.lux (which has a bunch of annoying issues with Intel Graphics, so Redshift is such a welcome initiative, also for Windows) I just put this little [Redshift Tray](https://github.com/ltGuillaume/Redshift-Tray) project on GitHub. It has a few more features like autorun, pause for x minutes, force night mode, double-click to enable/disabled, a beaut of an icon :P and -as stated - some optional hotkeys of my personal preference. Perhaps it could make someone else very happy, too :)

**Comment by manuc66** [comment]
There is also a project here : https://github.com/Nepochal/redshift-tray

**Comment by ltGuillaume** [comment]
Cool, I didn't find it on my search, and it still doesn't pop up in my search engine, strange! This caused me to choose the name for my project unwisely, sorry! :P I had a quick peek at the project, it's cool but somehow the automatic location option caused the program to crash on my system.

I was already looking into an option for automatic coordinates, so this caught my attention above all. I just released a new version with my own take on it, with an option "traveling", which will cause the program to check for new coordinates every time it (re)starts Redshift. This is ideal for when traveling with your laptop.

**Comment by Nepochal** [comment]
I uploaded a new release of https://github.com/Nepochal/redshift-tray a few moments ago. Thanks to @manuc66 I was able to fix the crash issue.

@ltGuillaume your program uses redshift and it shows a tray icon. Why not choose this appropriate name? So thats no problem to have two projects with the same name :)

**Comment by ltGuillaume** [comment]
:)

**Comment by jonls** [comment]
There seems to be a number of options available for Windows now. Closing this.
