### ISSUE TITLE
Include geoclue-2.0 as a dependency under Ubuntu rather than a recommended package

### ISSUE THREAD

**Issue by alexgleason** [jonls/redshift#439]
`apt show redshift` shows this.

```
Depends: libc6 (>= 2.17), libdrm2 (>= 2.4.3), libglib2.0-0 (>= 2.26.0), libx11-6, libxcb-randr0 (>= 1.3), libxcb1, libxxf86vm1
Recommends: geoclue-2.0
```

This is a problem, because installing Redshift with a GUI like software center or elementary's AppCenter offers no easy solution to users when they attempt to start Redshift and receive an error that geoclue2 isn't installed.

This makes it difficult for a layperson (someone without terminal experience) to install this package. They should be able to click "install" for the app, then launch it, and it "just works."

**Comment by MoonSweep** [comment]
On Debian (and, I guess, on Ubuntu), Recommends are installed by default. To have them not installed automatically when you install a package, you have to use a command-line option or add a configuration file to /etc/apt/apt.conf.d (that's what I do on my servers). Maybe that's what Elementary OS does, I don't know, I never used it; try looking in /etc/apt for something like:

```
// Install strict dependencies only
APT::Install-Recommends "0";
APT::Install-Suggests "0";
```

Redshift can be used without GeoClue since the location can be set manually, so the use of Recommends instead of Depends is perfectly justified : GeoClue will be installed by default (unless you specifically instructed apt not to do so, as I said above), but a user who wants to use Redshift by manually setting his/her location should still be able to remove GeoClue without apt removing Redshift because of the dependency. This is _exactly_ what Recommends were created for.

IMHO this issue should be closed.

**Comment by alexgleason** [comment]
I've confirmed that using apt from the terminal causes geoclue-2.0 to be installed. I also just tried with elementary's AppCenter again and it also caused geoclue-2.0 to be installed.

I may have been mistaken about what was happening, but I agree that if this were a problem it would have been on elementary's end. Regardless, it seems to be working fine there now too.

Thanks for the feedback!

**Comment by MoonSweep** [comment]
> Thanks for the feedback!

No problem. I stumbled upon this program and its Git repository seems to need some love, I'm no coder but I can help by triaging the bugs :)
