### ISSUE TITLE
Only 2 periods--day and night?

### ISSUE THREAD

**Issue by rieje** [jonls/redshift#442]
I'm confused--there's only 2 periods defined--day and night? Meaning there is a transition from day to night, but this transition seems to be extremely quick (maybe a couple of seconds) to go from one extreme (day) to another (night). 

Shouldn't the transition take place gradually over 12 hours? For example, at 4 AM it is 3500, at 7 AM it is 3800, at 10 AM it is 4500, at 1 PM it is 5700. 

What would a script look like if it could achieve this? 

At the moment, I can't use redshift without manually assigning different values every hour or so. I like my max and min temperatures but they need to be transitioned evenly, not over the course of a very short period of time (I think it's a few seconds, right?). This is particularly problematic because my max and min differences are massive and it's very frustrating only being able to have ideal temperatures perhaps 2 hours out of my 10+ hours of computer usage for work.

**Comment by chiraag-nataraj** [comment]
Hmm...I haven't seen this behavior (that is, I've found it gradual enough for my tastes). However, you could use `redshift -o` along with a cron script to have it periodically adjust the temperature.

**Comment by jonls** [comment]
There is a transition period between day and night defined by the solar elevation. By default it is daytime when the sun is above 3 degrees and nighttime below -6 degrees. In between is the transition period where the redness effect is gradually applied. The values for these thresholds can be adjusted in the configuration file by setting `elevation-high` and `elevation-low`. If you observe a transition of only a few seconds between night and day, it seems to indicate that something is not working correctly (or you have the elevation thresholds set very close). Since the transition period is defined by the solar elevation, the time it takes varies by location but should definitely be more than a few seconds.

**Comment by hrj** [comment]
Thanks for the clarification @jonis. It would be nice if these configuration settings (`elevation-high` and `elevation-low`) were also documented.

> Since the transition period is defined by the solar elevation, the time it takes varies by location but should definitely be more than a few seconds.

To be more precise, the transition period would vary by latitude as well as calendar date. If you live near Earth's poles and the date is closer to winter solstice, then transition period could be very quick, just a few seconds.

**Comment by jonls** [comment]
@hrj Even at the most extreme location it does not seem to be possible for the change in altitude from -3 degrees to 6 degrees to happen in only a few seconds. The configuration settings are documented in the man page.

@rieje and others: Since a few people seem to be having this issue (judging from the number of 👍 ) it would be helpful if someone could provide some more information, e.g. what is your location and did you change the `elevation-high` and `elevation-low`. Based on this we could figure out if this is a bug in Redshift. I'm going to close this issue since it is a few months old so please reopen it if any of you provide more information.

**Comment by hrj** [comment]
> Even at the most extreme location it does not seem to be possible for the change in altitude from -3 degrees to 6 degrees to happen in only a few seconds.

You are right. But I don't think I claimed that.

Anyway, I am happy with the current redshift heuristic, although it took a while to get used to it.

The only better way I can think of is to detect the amount of ambient light (through camera or an LDR), but that is too much work.
