### ISSUE TITLE
Possible to create Windows binary using Visual Studio?

### ISSUE THREAD

**Issue by robinhood2014** [jonls/redshift#460]
I'm attempting to create a Windows version of Redshift using Visual Studio instead of MinGW. After cloning the repository, I used VS's "Create Project From Existing Code" command to create the solution. Then, after retargeting the solution, I attempted to build it, and got all of this garglemesh.

https://1drv.ms/t/s!Aj9V_5x2ju0XnOZmywODNt4vKa6YSw

**Comment by jonls** [comment]
Does VS support C99 nowadays? It used to be that it didn't which means that it could not build Redshift. As far as I know it still doesn't. In case it does, you'd have to disable the X11 based adjustment methods since you don't have the header files for those on Windows. Take a look at the makefile to see how this should be done.

**Comment by jonls** [comment]
Closing this since there has been no more activity on this issue for a while.
