### ISSUE TITLE
How to restore color and gamma (Windows)?

### ISSUE THREAD

**Issue by thejustsoul** [jonls/redshift#517]
How to restore color and gamma? I run the program through the console (`redshift -c redshift.conf`), after a while shut it (`CTRL+C`), the gamma and brightness did not recover (it's understandable), but when I started it again, the gamma and brightness became even lower (if I run it a lot, the screen will darken completely) . How to fix it? How to properly turn off the program and rebuild the view?

`Windows 7 x64 SP1`, `redshift-i686`.

UPD: and how to apply ICC profile (monitor) for redshift? f.lux used ICC profile and the colors become softer, instead of yellow, it becomes more orange or something like that (3400K, but on redhift more yellow..).

**Comment by jonls** [comment]
Which version are you using (is preserve enabled)? This could be related to the bug that was identified in #513.

**Comment by thejustsoul** [comment]
@jonls `redshift 1.11`, need to downgrade?

**Comment by jonls** [comment]
Since there was no 1.11 Windows release I'm wondering if you are running the Windows release that was built from the master branch? The `preserve` option was recently changed to be enabled by default on the master branch. Previously, `preserve` could be enabled in the configuration file. The reason why this is important is due to the possible bug described in #513 which only occurs when `preserve` is enabled.

**Comment by thejustsoul** [comment]
I forgot where I downloaded the 1.11 version, but in history there is such a link to the [archive](https://ci.appveyor.com/api/projects/jonls/redshift/artifacts/redshift-windows-i686.zip?branch=master&job=Environment%3A+arch%3Di686&pr=false).

**Comment by jonls** [comment]
@thejustsoul Ok, thanks. This is the one that is built automatically from the master branch. Using an actual released version (e.g. 1.10) is recommended if you are not prepared to deal with debugging issues. I'm closing this issue since it seems to be due to the bug identified in #513.
