### ISSUE TITLE
Intermittent duplicate redshift-gtk icons in panel on Xubuntu 17.10

### ISSUE THREAD

**Issue by ulmus-scott** [jonls/redshift#582]
I have redshift-gtk setup to auto-start and intermittently I see two icons in the panel.  See the two screenshots below.

![panel_bug_redshift-gtk](https://user-images.githubusercontent.com/36139124/35782769-3466ec82-09cb-11e8-8e30-3c8b47d5546b.png)
![panel_bug_redshift-gtk_hidden](https://user-images.githubusercontent.com/36139124/35782804-b61350f4-09cb-11e8-8019-c66554c5354e.png)

The icon to the right of the network indicator is where it normally is.  As far as I can tell the issue is purely cosmetic and does not affect the functionality of redshift.  From what I can tell, the Notification Area in the panel is occasionally picking up redshift-gtk, in what seems to be a random manner.  

I have also had it start up normally with only one icon, but upon resuming from suspend, it then had two icons.

**Comment by jonls** [comment]
If there aren't actually multiple instances of Redshift running, this is likely an issue with the status bar implementation.

**Comment by AleSprea97** [comment]
Hi, the problem is that xfce use two plugins that basically do the same things: notification area (systray)  and status notifier plugin (statusnotifier), so sometimes the redshift icon appear two times. 
Source: https://askubuntu.com/questions/1119638/what-is-the-difference-between-notification-area-systray-indicator-plugin?rq=1
To solve the problem try to disable the appereance of redshift in one of the 2 (status notifier plugin in my case). 
Searching a way to solve the problem I found this page on Google as the first result, so I leave here the solution.
