### ISSUE TITLE
Redshift not working - Ubuntu 16.04, nvidia driver 384.111

### ISSUE THREAD

**Issue by manoskav** [jonls/redshift#590]
As the title says, Redshift doesn't seem to work after updating nvidia driver to 384.11. After rolling back to 340.104 it works as usual.

**Comment by tgrowl** [comment]
It does not appear to work on 390.25 either. I'm getting a lot of green tint when the temperature goes down.

**Comment by jshap70** [comment]
for future reference, the green tint is a separate but solvable issue: https://github.com/jonls/redshift/issues/587

**Comment by jonls** [comment]
Thanks for reporting this issue. This seems to be related to graphics drivers and not directly related to Redshift. While it's nice to have this information available for the users of Redshift, ultimately it's not the right place to discuss kernel/graphics driver issues since it's not something Redshift can do anything about. Please report this issue to your distribution or to the graphics driver maintainers.
