### ISSUE TITLE
Redshift is not working in Debian 9, Elementary OS 0.4.1 and Linux Mint 18.3

### ISSUE THREAD

**Issue by tiago4171** [jonls/redshift#593]
Hi,
I'm tryied to use redshift in those systems, but seem's this is not working. Simply in all of those systems the redshift doesn't change the color temperature.
I Don't know how to fix that. How I not found nothing recent in my searches I decided to open this issue.

Sorry for any concordance errors, english is not my native language
Kind regards
Tiago

**Comment by jonls** [comment]
Please see the FAQ first: https://github.com/jonls/redshift#faq Please reopen if the suggestions there did not help. It's possible that you are running Wayland instead of X which is not supported currently. Another issue could be that you graphics driver does not support adjustments to the gamma ramps.
