### ISSUE TITLE
amdgpu: Cursor color remains unchanged

### ISSUE THREAD

**Issue by ooglyhLL** [jonls/redshift#594]
After a recent switch from Intel HD4000 (internal) to an AMD R560 card, I noticed that the cursor color isn't affected by redshift. I tried all supported methods.

**Comment by jonls** [comment]
This is a known issue. Redshift is not able to affect hardware cursors.

**Comment by Quoor8ee** [comment]
Isn't it? Since linux-4.17rc on Polaris and Vega hardware (at least the ones I have access to), amdgpu even tints the cursor more strongly than the rest of the screen.
See my comment on https://github.com/jonls/redshift/issues/588#issuecomment-380634443, as well as  https://github.com/jonls/redshift/issues/623 (from which the cursor is more strongly affected than the rest of the screen, too).

**Comment by jonls** [comment]
It usually isn't implemented in graphics drivers/hardware when using hardware cursors but obviously it could be supported by the driver. In any case, there's no way Redshift can even check or influence whether this happens.
