### ISSUE TITLE
Flickering after upgrading to kernel 4.16.0

### ISSUE THREAD

**Issue by pager72** [jonls/redshift#601]
Using Redshift on gentoo and it was flickered somewhat but it was tolerable under kernel 4.14.0 but under 4.16.0 its intolerable and I have to disable it. I hope the issue is resolved, let me know if I need to provide any output.

**Comment by TillyMiso** [comment]
I to have flickering after kernel update. Running on 4.15.15

It flickers much just after i've started redshift, than it flickers every now and then randomly. I've two screens, they do not flicker simultaneously, its one screen at a time.

**Comment by skywalker89** [comment]
HI, have this issue since I updated to 18.04, same with the GNOME Night Light... so I came cack to Redshift, and it flickers less but still...any idea what causes this? Am on Kernel  4.16.1, but see this as mentioned since moce to 18.04 

it is really annoying

Thx a million

Dan

**Comment by pager72** [comment]
I downgraded to  4.15.11 less flickering but still happens. Using amdgpu driver.

**Comment by jonls** [comment]
Thanks for reporting this issue. This seems to be related to graphics drivers and not directly related to Redshift. While it's nice to have this information available for the users of Redshift, ultimately it's not the right place to discuss kernel/graphics driver issues since it's not something Redshift can do anything about.
