### ISSUE TITLE
Error in FAQ regarding location of the configuratoin file (PR attached)

### ISSUE THREAD

**Issue by hanslfc** [jonls/redshift#646]
Hi, 

I went trough setting up a custom `redshift.conf` file and tried to follow the FAQ guide in the Readme. In seems there is a typo:
If I follow the current guide and put the config file under `~/.config/redshift/redshift.conf` it seems to be without effect. However if it is located in `~/.config/redshift.conf`, configurations are applied as expected. 

I hence assume this is a typo in the readme which might cause confusion to other and thus should be fixed. :bowing_man: 

Attached a PR which changes these lines in the Readme,

**Comment by jonls** [comment]
The README applies to the most recent release (1.12) which will look in `~/.config/redshift/redshift.conf` (and also `~/.config/redshift.conf` but this location is deprecated since all config files should be under a single directory). Older releases will only look in `~/.config/redshift.conf` as you have discovered. It may be better to look at the README installed by your distribution instead of the one on GitHub as that would apply to your currently installed version.
