### ISSUE TITLE
Location Provider Backup

### ISSUE THREAD

**Issue by jlosito** [jonls/redshift#660]
Is there a way in which one can provide multiple location providers? For instance, geoclue2 being the primary and manual being the secondary.

The issue that I'm having is that I prefer to get my location from geoclue2, but if I am unable to get an internet connection, I won't get a location. Furthermore, due to the lack of location, redshift will not start.

I understand that redshift's configuration file uses ini. Therefore, one can not provide a list as values. Instead, can redshift use toml? This would provide backwards capability as well as the additional feature of primary and secondary providers.

**Comment by jonls** [comment]
Thanks for the suggestion. Redshift 1.12 should start fine even if GeoClue cannot provide a location immediately. GeoClue will wait until an internet connection becomes available and then provide Redshift with the location. There's been some talk of storing a cache of the last location so that Redshift can start working with that location while waiting for the location provider. This seems like a reasonable solution that might also fix your issue. I think also reworking the manual location provider so that the manual location can be used in those cases would be reasonable. I don't see why Redshift would need TOML for this, all of these options (even if we go with some option where the user can specify multiple location providers) should easily be possible with the current format.
