### ISSUE TITLE
temp-day doesn't set the daytime temperature

### ISSUE THREAD

**Issue by EliaTarasoff** [jonls/redshift#718]
## Description
`temp-day` in `~/.config/redshift/redshift.conf` doesn't set the daytime temperature.

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mentioned there.

## Steps To Reproduce
1. Set `temp-day` in `~/.config/redshift/redshift.conf`.
1. Restart redshift.
1. Observe the daytime temperature not getting changed.

## Expected behavior
`temp-day` should set the daytime temperature.

## Error output / Logs / Screenshots / Etc
- ![temp-day](https://user-images.githubusercontent.com/17089991/57702055-796e2680-761a-11e9-9431-6c8428d5e366.png)
- Redshift's not even using the [default temperature of 6500](https://github.com/jonls/redshift/blob/01139a15bfd9c2882871f26d915495e14dd2ba7a/src/options.c#L50); 5500 isn't anywhere in the source / defaults as far as I can see.

## Software Versions
 - OS: Linux
 - Redshift version: 1.11
 - Distribution: 	Xubutntu (`lsb_release -a` shows `Ubuntu 18.04.2 LTS`)
 - Redshift installed from: default GUI-based software manager (it's just a wrapper over apt-get - it locks access to apt stuff while it's doing updates)

**Comment by joleeee** [comment]
Are you sure the config is actually getting loaded? What happens if you specify lat / lon manually, if you haven't already?

**Comment by infrontoftheforest** [comment]
On version 1.11, the file should be just `~/.config/redshift.conf`, not `~/.config/redshift/redshift.conf` The information from the FAQ is for v1.12. [Here is the line where it searches for the .conf file in tag v1.11](https://github.com/jonls/redshift/blob/f83b005c3bab866129985f780c9669109d863725/src/config-ini.c#L66). I had this same issue, since v1.11 is distributed in the apt repositories, but coming here for information gives the info for v1.12.

**Comment by EliaTarasoff** [comment]
So annoying. Thanks for the info! `^^;`
