### ISSUE TITLE
Time-based adjustment.

### ISSUE THREAD

**Issue by akvadrako** [jonls/redshift#744]
**Is your feature request related to a problem? Please describe.**

I don't care when the sun has set, since it's very different in the summer and winter. I like to change color temp based on the time.

**Describe the solution you'd like**

Instead of location, I would like redshift to adjust the temp based on the time.

**Describe alternatives you've considered**

I set the lat/lon to 0/0 manually, but this isn't what I want.

**Additional context**

**Comment by jgg1971** [comment]
I would like this feature too. Or even better, that in the configuration file you could set the working hours. In my case, I don't like it to be active in the early morning (let's say from 5:00 onwards) because the blue light helps me to get fully awaken (and it should help the circadian rhythm). I would love redshift to be working in the evening (the ways it does), and being "stand-by" in the morning.
I have considered an alternative: not starting it automatically, and starting it from cron in the afternoon; but it feels somehow cumbersome.

**Comment by jonls** [comment]
This already exists since version 1.12.

**Comment by akvadrako** [comment]
Cool, I had no idea. Maybe I would have found it if documented in the sample config on http://jonls.dk/redshift/
