### ISSUE TITLE
Redshift stops adjusting after a few seconds

### ISSUE THREAD

**Issue by smicca** [jonls/redshift#786]
When adjusting the temperature using -O, the screen changes momentarily, then returns back.

https://user-images.githubusercontent.com/55837502/102813473-dbfedb00-4396-11eb-92c9-69d58874eaaa.mp4

Also, when adjusting location, the terminal freezes and nothing else can be entered:

https://user-images.githubusercontent.com/55837502/102813301-9215f500-4396-11eb-8053-314f590d6fc6.mp4

**Comment by smicca** [comment]
I got it to work another way. In terminal I entered:
redshift -t 3500:3500

After this, it started switching every second between 3500K and the original 6500K. Then I right clicked the icon on the bottom right taskbar, hit quit, and it stayed at 3500K.

**Comment by basil-conto** [comment]
I think I'm seeing something similar on Debian Testing with X and `redshift` and `redshift-gtk` v1.12-4.

Stopping `redshift.service` makes it flicker on/off a bit more but then it finally settles (with `redshift-gtk.service` still on).

**Comment by basil-conto** [comment]
After purging and reinstalling the packages, and removing the manual `location-provider` settings I had in `~/.config/redshift.conf`, the flickering is no longer happening.

**Comment by smicca** [comment]
Where is the ~/.config/redshift.conf located? I tried searching all system files for redshift.conf but the only thing that appeared was example-redshift.conf.

And what gets removed? Here's what I see in the example file: 
![image](https://user-images.githubusercontent.com/55837502/102845043-ab409500-43da-11eb-83de-573b0b369078.png)

**Comment by basil-conto** [comment]
> Where is the ~/.config/redshift.conf located?

At `~/.config/redshift.conf`, of course! ;)

It's where the user's optional configuration file goes - I added this file myself.

See the section `CONFIGURATION FILE` of `man 1 redshift`.

> And what gets removed?

This is what my configuration looked like before `redshift` started flashing:

```gitconfig
[redshift]
brightness-night=0.8
location-provider=manual
temp-night=3000

[manual]
lat=53.4
lon=-6.3
```

I deleted this file and reinstalled `redshift` and there was no more flashing. So I started adding some of my configuration back:

```gitconfig
[redshift]
brightness-night=0.8
temp-night=3000
```

I had added the manual location settings because I was running into an issue like that in #265, but I guess that's been fixed for me now, so I didn't bother adding those settings back.  I haven't noticed any flickering since my last message.

**Comment by smicca** [comment]
I made the .conf file with those three lines. Does redshift automatically pick up on it or does it have to be run? If so, how is that done?

Edit: Just saw the -c FILE option on the man 1 page. Thanks for all your help.

**Comment by basil-conto** [comment]
> I made the .conf file with those three lines.

Why? This file is just my personal configuration for temperature settings. The only reason I mentioned it is because either reinstalling `redshift`, or removing the manual location settings, or both, fixed the issue for me.  If you don't have a configuration file to begin with then you have no settings to remove.

> Does redshift automatically pick up on it or does it have to be run?

`redshift` reads the configuration file when it starts. So, if you edit the configuration while `redshift` is running, and want the new settings to take effect, then you need to restart `redshift`.

**Comment by smicca** [comment]
Using redshift -c ~/.config/redshift.conf worked perfectly, now it automatically starts each time the computer boots. 

Before, the flicker happened when any other command was used, like redshift -t 3500:3500, so -c is the way to go.

Here's what's in the .conf file for reference:
[redshift]
brightness-night=0.6
temp-night=3000
temp-day=3500
brightness-day=.8
location-provider=manual
[manual]
lat=42.1
lon=-75.3

Thanks again.
