### ISSUE TITLE
Ubuntu package is out of date

### ISSUE THREAD

**Issue by shanemd** [jonls/redshift#803]
It looks like launchpad isn't watched any more so I'm posting this here.

The package in the Ubuntu repos is 1.10. The latest is 1.12 as of this bug filing.

What needs to be done to get that updated? Can I help?

**Comment by hartwork** [comment]
Hi @shanemd,

thanks for offering help! Looking at https://packages.ubuntu.com/hirsute/redshift I can see that _recent_ Ubuntu does have redshift 1.12 packaged. If your Ubuntu has redshift as old as 1.10 that probably means you're running a version of Ubuntu as old as Xenial/16.04 which is 6(!) years old and will be [end of life in only about just two months from now](https://wiki.ubuntu.com/Releases). A way to check which Ubuntu you are running would be command `cat /etc/os-release` in a terminal, for example. So the fix needs to happen somewhere on your side: Please consider upgrading to a more recent version of Ubuntu e.g. 20.04 LTS or 20.10.
On a side note, redshift "[upstream](https://en.wikipedia.org/wiki/Upstream_(software_development))" here does not control Ubuntu packaging "[downstream](https://en.wikipedia.org/wiki/Downstream_(software_development))". If you run into similar situations in the future, please approach Ubuntu package maintainers downstream rather than the project upstream. What do you think?

Best, Sebastian

**Comment by shanemd** [comment]
He Sebastian,

Thanks for checking on this and getting back with me. I am in fact running Ubuntu 16.04 (this is a work computer, and that's what the company requires right now...). However, according to the Ubuntu releases page you linked, 16.04 doesn't go EOL until April of 2024. In two months it goes into "End of standard support" though, which I expect is what you were referring to.

I'm still interested in getting the package updated in the 16.04 repositories though, Thank you for pointing me in the right direction!

Here's the bug I filed on launchpad (it looks like that's the right place to put things like this), we'll see what happens: https://bugs.launchpad.net/ubuntu/+source/redshift/+bug/1914880

**Comment by hartwork** [comment]
> Thanks for checking on this and getting back with me. I am in fact running Ubuntu 16.04 (this is a work computer, and that's what the company requires right now...). However, according to the Ubuntu releases page you linked, 16.04 doesn't go EOL until April of 2024. In two months it goes into "End of standard support" though, which I expect is what you were referring to.

You're right, yes!
I re-checked [what "standard support" means](https://wiki.ubuntu.com/SecurityTeam/FAQ#Standard_Support) just now. Unless your employer pays for [Extended Security Maintenance](https://ubuntu.com/security/esm) with Canonical, you'll be entering "very vulnerable zone" in April (and you are far away from non-security bugfixes already today).


> I'm still interested in getting the package updated in the 16.04 repositories though,

I doubt that's something they will do. Distro releases are frozen at some point. After that's security fixes, no regular bugfixes, no new features. That's what you sign up for with LTS: for a somewhat secure copy of the past.


> Here's the bug I filed on launchpad (it looks like that's the right place to put things like this), we'll see what happens: https://bugs.launchpad.net/ubuntu/+source/redshift/+bug/1914880

Seems like the right place.

Since the redshift package is in section `universe`: I have extended [my blog post on my personal encounter with missing security fixes in a `universe` package of an Ubuntu LTS release](https://blog.hartwork.org/posts/why-i-recommend-debian-over-ubuntu-by-now/) and what I learned from it, just now, if you're curious.

With regard to redshift *upstream*, is there anything more to be done right here?

**Comment by shanemd** [comment]
Thanks Sebastian. I appreciate your clear thorough responses. It's always a crapshoot with open source projects. Sometimes I just get nothing back from the maintainers at all, for months, or ever. Much appreciated.

I think as far as redshift upstream is concerned, this issue can be closed. Thank you helping guide this in the right direction.

**Comment by hartwork** [comment]
> Thanks Sebastian. I appreciate your clear thorough responses. It's always a crapshoot with open source projects. Sometimes I just get nothing back from the maintainers at all, for months, or ever. Much appreciated.

Understood. I'll save a more detailed reply here in the interest of staying on topic. I hope that's okay.

> I think as far as redshift upstream is concerned, this issue can be closed. Thank you helping guide this in the right direction.

Okay cool. I lack write permissions here — I maintain the Gentoo packaging of redshift and just felt like jumping in here, today. If you can close the issue yourself, that would be nice and fastest.

**Comment by shanemd** [comment]
> If you can close the issue yourself, that would be nice and fastest.

Got it. I'll go ahead and close it.

> Understood. I'll save a more detailed reply here in the interest of staying on topic. I hope that's okay.

Totally okay. I'd be happy to chat in some other format if you want. Does GitHub have direct messages of some form?

**Comment by hartwork** [comment]
> Totally okay. I'd be happy to chat in some other format if you want. Does GitHub have direct messages of some form?

Not that I'm aware of. I found an e-mail address of yours at https://github.com/shanemd/mtimer/commit/2b3b930eafb62fbb1c138187af0bd9d41be58290.patch and just sent mail to you.
